### ISSUE TITLE
Provide way of creating translations values without decoding JSON

### ISSUE THREAD

**Issue by ChristophP** [ChristophP/elm-i18next#21]
1. Implement string : `String -> Tree` as an alias for Leaf
2. Implement object : `List (String, Tree) -> Tree` using Branch
3. Implement fromTree : `List (String, Tree) -> Translations`, using foldTree and Translations. I would expect a list as input here. If it were just a Tree someone could pass a string value as a root object, which couldn't be handled by t. That would make fromTree look like this:
```elm
translations =
    I18Next.fromTree
      [ ("custom"
        , object
            [ ( "morning", string "Morning" )
            , ( "evening", string "Evening" )
            , ( "afternoon", string "Afternoon" )
            ]
        )
      , ("hello", string "hello")
     ]
```
4. Expose `Tree`, `string`, `object`, `fromTree` and write a tests checking if t return the correct values when given a translations value that is custom built.

Would you want to give the implementation a try? I can also do it but it'll likely be sometime next week till I find time.

**Comment by ChristophP** [comment]
@Tehnix It's done and released. Hope this solves your use case.

**Comment by Tehnix** [comment]
@ChristophP thanks so much for setting time away for this, it solves it perfectly while also accommodating the more complex cases! :)

**Comment by ChristophP** [comment]
@Tehnix Sweet, glad it helps. :-)
