### ISSUE TITLE
Could we set the HTML lang attribute based on selected locale?

### ISSUE THREAD

**Issue by mccrodp** [ChristophP/elm-i18next#4]
Do you think this is something possible with Elm and something for this repo?

When I'm swapping between translations I'd like change the HTML's lang to match translations loaded.

Also I have all my string loaded via translations now :) But I noticed the string JSON keys flash up first, is their anyway to avoid that flash? http://ahimsayoga.jp

Code here: https://github.com/ahimsayoga/brunch-with-elm-bootstrap/blob/master/app/elm/Main.elm#L76

Thanks

**Comment by ChristophP** [comment]
So about the HTML lang attribute: I the only way to do that is using ports in your application since you can't really rouch the lang attribute of the HTML tag in elm.

**Comment by ChristophP** [comment]
Regarding the flash of translation keys. There is 2 ways to avoid that.
1. declare Translations as a Maybe in your Model and set it to Nothing initially. update it to Just ... when your translations are loaded. In your view render some spinner first and then your page content when the translations are there.
2. Preload the translations with JS and pass them into as flags. Check the readme section "Using preloaded Translations" on how to do it. You could even cache the translations the localstorage if you want.

**Comment by mccrodp** [comment]
That's great info, thanks. I'll check out the README for No. 2. by preloading with JS and using flags.

For using ports I imagine this is also a JS interop. Will do some research. Many thanks.

In the middle of swapping my routing parser / routing method from https://github.com/Bogdanp/elm-route/ to https://github.com/evancz/url-parser as was having issues parsing simple `en/about` route. Will post back here after that.

**Comment by ChristophP** [comment]
Yeah I have been using  https://github.com/evancz/url-parser before and it was wokring well for me. Let me know.

**Comment by ChristophP** [comment]
Seems resolved or inactive. Closing for now.
