### ISSUE TITLE
Example is wrongly using "button" key but it's called "greetings"

### ISSUE THREAD

**Issue by muelli** [ChristophP/elm-i18next#6]
the example file seems to have wrong content:

https://github.com/ChristophP/elm-i18next/blob/d4e29fd8223a1f32adbd836b275ef69945c78b5a/examples/Regular.elm#L76

but there is no "buttons" key:
https://github.com/ChristophP/elm-i18next/blob/d4e29fd8223a1f32adbd836b275ef69945c78b5a/examples/Regular.elm#L22-L24

**Comment by ChristophP** [comment]
Good catch :+1: I will change it.

**Comment by ChristophP** [comment]
Fixed for new version https://github.com/ChristophP/elm-i18next/blob/52f9bbeaaeff05b1c4521893d5d22f9491d2071c/examples/Regular.elm
